AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/HeredocDelimiterNaming:
  Enabled: false